version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "tvksp"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    networks:
      - monitoring
  app:
    image: martell805/tvksp4:latest
    container_name: tvksp4
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - monitoring

  graylog:
    image: graylog/graylog:4.2
    environment:
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_ROOT_PASSWORD_SHA2: "your_graylog_password_hash"
      GRAYLOG_PASSWORD_SECRET: "some_random_secret"
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
    networks:
      - monitoring

  mongo:
    image: mongo:4.2
    networks:
      - monitoring

  elasticsearch:
    image: elasticsearch:8.15.2
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - monitoring

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - monitoring

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    environment:
      DB_SERVER_HOST: "postgres"
      POSTGRES_DB: "tvksp"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "10051:10051"
    depends_on:
      - postgres
    networks:
      - monitoring

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: "postgres"
      POSTGRES_DB: "tvksp"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "8082:8080"
    depends_on:
      - zabbix-server
      - postgres
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring

volumes:
  postgres-data:

networks:
  monitoring: