spring:
  application:
    name: TVKSP4
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tvksp}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
